### ISSUE TITLE
UI improvement: keep quiz alternatives in the same place when giving feedback

### ISSUE THREAD

**Issue by eliasdorneles** [eliasdorneles/equalizer-game#3]
Currently, when the user answer the quiz, we redraw all the alternatives, putting the correct alternative at the left, and the incorrect one at the right if user gave the wrong answer.

This was a bit of an afterthought decision of mine when coding the first version, it made some things more convenient in the code that I already forget what it was.

I discussed this w/ @antoineterny who suggested it will be best to keep the alternatives where they are after the user answers (we could do something like add opacity for the incorrect ones).

**Comment by antoineterny** [comment]
Here is what it would look like after an answer 
![EQ game answer](https://user-images.githubusercontent.com/63339704/82459408-33af2e00-9ab8-11ea-8a95-e1cf62b33d10.png)

**Comment by eliasdorneles** [comment]
Yesss, that's what I was having in mind! :heart_eyes: 
Thanks for the mockup!

**Comment by eliasdorneles** [comment]
Hm, but now I need to figure out the placement of this button:

![image](https://user-images.githubusercontent.com/37565/82571337-1c894280-9b83-11ea-9ef7-ee379c2b7de8.png)

:thinking:

**Comment by antoineterny** [comment]
Maybe, after the game is played, it would be good to be able to listen to each equalization by clicking on it. In this case, there would be no need anymore for this button ?

**Comment by antoineterny** [comment]
And by the way, maybe the color convention (green is right, red is wrong) is not clear enough, so the opacity would be better that way in case of wrong answer :
![image](https://user-images.githubusercontent.com/63339704/82575077-44c77000-9b88-11ea-852c-394ec1eecf59.png)

**Comment by eliasdorneles** [comment]
> Maybe, after the game is played, it would be good to be able to listen to each equalization by clicking on it. In this case, there would be no need anymore for this button ?

I don't think anyone will be able to guess that behavior.

It's really best to have a button and that the button is next to it. In the initial version, I showed the button on the top and people missed it.

Maybe it's fine to just take the extra space and whatever :man_shrugging: 
It may be not that great esthetically, but I'm thinking it's the best UI.
